version: '3.8'
services:
  movies:
    image: saikrishnamathi81/movie:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: saikrishnamathi81/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: saikrishnamathi81/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: saikrishnamathi81/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
